# Generated by Django 3.1.4 on 2020-12-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('nm', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
